services:
  api:
    expose:
      - ${PORT}
    image: nikolakozaryan/nodejs2024q3-service-api
    restart: on-failure
    networks:
      - service-network
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./src:/app/src
  postgres:
    expose:
      - ${POSTGRES_PORT}
    image: nikolakozaryan/nodejs2024q3-service-postgres
    restart: on-failure
    networks:
      - service-network
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-logs:/var/log/postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  db-data:
  db-logs:

networks:
  service-network:
    driver: bridge
